services:
  db:
    image: mysql:8.0
    container_name: mysql_bank_app_analysis
    ports:
      - "3306:3306"
    environment:
      # Define la contraseña root
      MYSQL_ROOT_PASSWORD: 'admin'
      # Crea la base de datos automáticamente
      MYSQL_DATABASE: 'bank_app_analysis'
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data: